FROM hydronautics/severov_auv:xavier

WORKDIR /severov_auv
COPY src src
COPY *.sh /severov_auv/
RUN /bin/bash -c "source /additional_packages/install/setup.bash && /severov_auv/build_vision.sh"

RUN echo 'source /severov_auv/install/setup.bash' >> /root/.bashrc

ENTRYPOINT [ "/severov_auv/run_vision.sh" ]

CMD ["bash"]
